# LLM RAG Project Configuration

# API Keys (set these as environment variables for security)
api_keys:
  kimi_api_key: "sk-sSqWIxpm0Y6vk35c3OsZNLDn6LpPNZHJ8NAfFaAxhYkWkkFw"
  siliconflow_api_key: "sk-evutupykegqtffjcjhhcezzakgvsojlshgaazhbjvflmjorg"

# Embedding Configuration
embedding:
  provider: "siliconflow"
  model: "BAAI/bge-large-zh-v1.5"
  api_base: "https://api.siliconflow.cn/v1"
  dimension: 1024
  batch_size: 32
  max_retries: 3

# LLM Configuration
llm:
  provider: "kimi"
  model: "moonshot-v1-8k"
  api_base: "https://api.moonshot.cn/v1"
  max_tokens: 4096
  temperature: 0.7
  max_retries: 3

# Milvus Configuration
milvus:
  host: "localhost"
  port: 19530
  collection_name: "document_collection"
  index_type: "IVF_FLAT"
  metric_type: "COSINE"  # 使用余弦相似度
  nlist: 1024
  search_params:
    nprobe: 16

# Document Processing
document:
  chunk_size: 512
  chunk_overlap: 50
  supported_formats: [".pdf", ".txt", ".md", ".docx"]
  max_file_size: 10485760  # 10MB in bytes

# Retrieval Configuration
retrieval:
  top_k: 5
  similarity_threshold: 0.3  # 余弦相似度阈值，0-1范围，0.3为合理阈值
  dense_weight: 0.7
  sparse_weight: 0.3
  rerank: true

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  title: "LLM RAG API"
  description: "智能问答系统API"
  version: "1.0.0"

# Web Configuration
web:
  title: "智能问答系统"
  max_upload_size: 10485760  # 10MB
  page_config:
    page_title: "LLM RAG"
    layout: "wide"

# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  rotation: "1 week"
  retention: "1 month"

# Conversation Management Configuration
conversation:
  # 会话管理
  storage_dir: "./data/sessions"
  enable_compression: true
  enable_checkpoints: true
  
  # 上下文压缩配置
  compression:
    max_uncompressed_messages: 20
    compression_ratio: 0.3
    preserve_recent_messages: 5
    
  # 检查点配置
  checkpoints:
    auto_checkpoint_interval: 10  # 每10条消息自动创建检查点
    max_checkpoints_per_session: 5
    
  # 会话清理
  cleanup:
    auto_cleanup_days: 30
    max_sessions: 1000

# LangGraph Configuration
langgraph:
  # 工作流配置
  workflow:
    max_concurrency: 10
    timeout: 300  # 5分钟超时
    enable_checkpointing: true
    
  # 状态管理配置
  state:
    persist_messages: true
    max_history_length: 50
    
  # 节点配置
  nodes:
    intent_recognizer:
      confidence_threshold: 0.5
    document_processor:
      max_file_size: 10485760  # 10MB
      temp_dir: "./temp"
    retriever:
      default_top_k: 5
      enable_caching: true
    generator:
      max_context_tokens: 8000
      temperature: 0.7